services:
  api:
    container_name: membership-api
    build:
      context: ./src/api/Api.Membership
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=MembershipDb;User=sa;Password=Nabin@123;TrustServerCertificate=True;
    depends_on:
      - db
    restart: always

  db:
    container_name: membership-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Nabin@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    restart: always

  ui:
    container_name: membership-ui
    build:
      context: ./src/ui/membership-app
    ports:
      - "4200:80"
    depends_on:
      - api
    restart: always

volumes:
  mssql-data: